(function(g){var window=this;var SAa=function(a,b){return g.Rb(a,b)},Q6=function(a){g.Cm(a,"zx",g.vb());
return a},R6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Fm(a.g,b,c)},TAa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.$C.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.ZC(b)&&c.push(a):c.push(a)},a);
return c},UAa=function(a,b){var c=TAa(a,b);
(0,g.C)(c,function(a){g.$C.prototype.remove.call(this,a)},a)},VAa=function(a){if(a.yd){if(a.yd.locationOverrideToken)return{locationOverrideToken:a.yd.locationOverrideToken};
if(null!=a.yd.latitudeE7&&null!=a.yd.longitudeE7)return{latitudeE7:a.yd.latitudeE7,longitudeE7:a.yd.longitudeE7}}return null},WAa=function(a,b,c,d){var e=new g.tm(null,void 0);
a&&g.um(e,a);b&&g.vm(e,b);c&&g.wm(e,c);d&&g.xm(e,d);return e},XAa=function(a){g.OF[a]&&(a=g.OF[a],(0,g.C)(a,function(a){g.MF[a]&&delete g.MF[a]}),a.length=0)},YAa=function(a){var b=g.LF();
if(b)if(b.clear(a),a)XAa(a);else for(var c in g.OF)XAa(c)},S6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.nm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ZAa(this,a.capabilities||""),$Aa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},ZAa=function(a,b){a.capabilities.clear();
(0,g.Id)(b.split(","),g.Ea(SAa,aBa)).forEach(function(b){a.capabilities.add(b)})},$Aa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},T6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},U6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},bBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cBa=function(a){return new T6(a)},dBa=function(a){return g.ya(a)?(0,g.I)(a,cBa):[]},V6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},W6=function(a){return g.ya(a)?"["+(0,g.I)(a,V6).join(",")+"]":"null"},X6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},eBa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Y6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},Z6=function(a,b){return g.Ja(a,function(a){return U6(a,b)})},fBa=function(){var a=(0,g.HG)();
a&&UAa(a,a.g.Od(!0))},$6=function(){var a=g.KG("yt-remote-connected-devices")||[];
g.db(a);return a},gBa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},hBa=function(a){g.JG("yt-remote-connected-devices",a,86400)},b7=function(){if(a7)return a7;
var a=g.KG("yt-remote-device-id");a||(a=X6(),g.JG("yt-remote-device-id",a,31536E3));for(var b=$6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return a7=d},c7=function(){var a=$6(),b=b7();
g.Na(a,b);g.MG()&&g.fb(a,b);a=gBa(a);if(g.Oa(a))try{g.uG("remote_sid")}catch(c){}else try{g.tG("remote_sid",a.join(","),-1)}catch(c){}},iBa=function(){return g.KG("yt-remote-session-browser-channel")},jBa=function(){return g.KG("yt-remote-local-screens")||[]},kBa=function(){g.JG("yt-remote-lounge-token-expiration",!0,86400)},lBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(jBa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.bm)(c,function(a){return!g.Na(b,a)})&&kBa();
g.JG("yt-remote-local-screens",a,31536E3)},mBa=function(a,b){g.JG("yt-remote-session-browser-channel",a);
g.JG("yt-remote-session-screen-id",b);var c=$6(),d=b7();g.Na(c,d)||c.push(d);hBa(c);c7()},d7=function(a){a||(g.LG("yt-remote-session-screen-id"),g.LG("yt-remote-session-video-id"));
c7();a=$6();g.Sa(a,b7());hBa(a)},nBa=function(){if(!e7){var a=g.kD();
a&&(e7=new g.UC(a))}return e7?!!e7.get("yt-remote-use-staging-server"):!1},oBa=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},pBa=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},qBa=function(){var a=oBa(),b=window.document.getElementById(a),c=b&&g.XE(b,"loaded");
c||b&&!c||(b=pBa(a,function(){g.XE(b,"loaded")||(g.WE(b,"loaded","true"),g.SF(a),g.TD(g.Ea(YAa,a),0))}))},f7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},rBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g7=function(a){a.length?sBa(a.shift(),function(){g7(a)}):h7()},tBa=function(a){return"chrome-extension://"+a+i7},sBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},j7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},h7=function(){var a=rBa();
a&&a(!1,"No cast extension found")},k7=function(){if(uBa){var a=2,b=rBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;sBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h7,c)}},vBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(k7(),a({command:"cast.sender.init"}))},wBa=function(){k7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);g7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+i7,"//www.gstatic.com/eureka/clank"+i7])},l7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.pd=b;this.B=(0,g.A)(this.HI,this);this.g=!1;this.l=0;this.o=this.Aa=null;this.A=[]},m7=function(){},n7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Jm(this);this.l=new g.pg;this.l.setInterval(250)},yBa=function(a,b,c){a.Aj=1;
a.eh=Q6(b.clone());a.Gi=c;a.B=!0;xBa(a,null)},o7=function(a,b,c,d,e){a.Aj=1;
a.eh=Q6(b.clone());a.Gi=null;a.B=c;e&&(a.gD=!1);xBa(a,d)},xBa=function(a,b){a.ik=(0,g.G)();
p7(a);a.Ch=a.eh.clone();R6(a.Ch,"t",a.C);a.pm=0;a.Qc=a.g.ir(a.g.dm()?b:null);0<a.Nr&&(a.fp=new g.Uk((0,g.A)(a.tE,a,a.Qc),a.Nr));a.W.T(a.Qc,"readystatechange",a.eU);var c=a.hi?g.Zb(a.hi):{};a.Gi?(a.Rp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Ch,a.Rp,a.Gi,c)):(a.Rp="GET",a.gD&&!g.xd&&(c.Connection="close"),a.Qc.send(a.Ch,a.Rp,null,c));a.g.tf(1)},BBa=function(a,b,c){for(var d=!0;!a.Rh&&a.pm<c.length;){var e=zBa(a,c);
if(e==q7){4==b&&(a.fh=4,r7(15),d=!1);break}else if(e==ABa){a.fh=4;r7(16);d=!1;break}else s7(a,e)}4==b&&0==c.length&&(a.fh=1,r7(17),d=!1);a.zf=a.zf&&d;d||(t7(a),u7(a))},zBa=function(a,b){var c=a.pm,d=b.indexOf("\n",c);
if(-1==d)return q7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return ABa;d+=1;if(d+c>b.length)return q7;var e=b.substr(d,c);a.pm=d+c;return e},DBa=function(a,b){a.ik=(0,g.G)();
p7(a);var c=b?window.location.hostname:"";a.Ch=a.eh.clone();g.Cm(a.Ch,"DOMAIN",c);g.Cm(a.Ch,"t",a.C);try{a.Af=new window.ActiveXObject("htmlfile")}catch(n){t7(a);a.fh=7;r7(22);u7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in v7)k=v7[l];else if(l in CBa)k=v7[l]=CBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=v7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.uc("b/12014412"),d);a.Af.open();a.Af.write(g.Qc(c));a.Af.close();a.Af.parentWindow.m=(0,g.A)(a.kT,a);a.Af.parentWindow.d=(0,g.A)(a.tC,a,!0);a.Af.parentWindow.rpcClose=(0,g.A)(a.tC,a,!1);c=a.Af.createElement("DIV");a.Af.parentWindow.document.body.appendChild(c);d=g.Hc(a.Ch.toString());d=g.ob(g.Ec(d));d=g.Zc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);
a.g.tf(1)},p7=function(a){a.tv=(0,g.G)()+a.A;
EBa(a,a.A)},EBa=function(a,b){if(null!=a.Ak)throw Error("WatchDog timer not null");
a.Ak=w7((0,g.A)(a.AT,a),b)},x7=function(a){a.Ak&&(g.x.clearTimeout(a.Ak),a.Ak=null)},u7=function(a){a.g.Dy()||a.Rh||a.g.Qo(a)},t7=function(a){x7(a);
g.Ye(a.fp);a.fp=null;a.l.stop();g.Pm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Af&&(a.Af=null)},s7=function(a,b){try{a.g.mC(a,b),a.g.tf(4)}catch(c){}},GBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;FBa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){GBa(a,b,c,d,f)},f)})}},FBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{y7(d),c(!0)}catch(e){}};
d.onerror=function(){try{y7(d),c(!1)}catch(e){}};
d.onabort=function(){try{y7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{y7(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},y7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},HBa=function(a){this.g=a;
this.l=new m7},IBa=function(a){var b=z7(a.g,a.Gk,"/mail/images/cleardot.gif");
Q6(b);GBa(b.toString(),5E3,(0,g.A)(a.TH,a),3,2E3);a.tf(1)},B7=function(a){var b=a.g.H;
if(null!=b)r7(5),b?(r7(11),A7(a.g,a,!1)):(r7(12),A7(a.g,a,!0));else if(a.pe=new n7(a,void 0,void 0,void 0),a.pe.hi=a.Lr,b=a.g,b=z7(b,b.dm()?a.fl:null,a.Mr),r7(5),!g.vd||g.oc(10))R6(b,"TYPE","xmlhttp"),o7(a.pe,b,!1,a.fl,!1);else{R6(b,"TYPE","html");var c=a.pe;a=!!a.fl;c.Aj=3;c.eh=Q6(b.clone());DBa(c,a)}},C7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new m7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},JBa=function(a,b){this.g=a;
this.map=b;this.context=null},KBa=function(a){g.$e.call(this,"statevent",a)},LBa=function(a,b){g.$e.call(this,"timingevent",a);
this.size=b},MBa=function(a){g.$e.call(this,"serverreachability",a)},PBa=function(a){NBa(a);
if(3==a.g){var b=a.Kl++,c=a.Hn.clone();g.Cm(c,"SID",a.o);g.Cm(c,"RID",b);g.Cm(c,"TYPE","terminate");D7(a,c);b=new n7(a,a.o,b,void 0);b.Aj=2;b.eh=Q6(c.clone());(new window.Image).src=b.eh;b.ik=(0,g.G)();p7(b)}OBa(a)},QBa=function(a){a.pI(1,0);
a.Hn=z7(a,null,a.Kr);E7(a)},NBa=function(a){a.Vg&&(a.Vg.abort(),a.Vg=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.ng&&(g.x.clearTimeout(a.ng),a.ng=null);F7(a);a.Ud&&(a.Ud.cancel(),a.Ud=null);a.Xg&&(g.x.clearTimeout(a.Xg),a.Xg=null)},RBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new JBa(a.ZO++,b));2!=a.g&&3!=a.g||E7(a)},E7=function(a){a.Ud||a.Xg||(a.Xg=w7((0,g.A)(a.rC,a),0),a.mj=0)},TBa=function(a,b){if(1==a.g){if(!b){a.Kl=Math.floor(1E5*Math.random());
var c=a.Kl++,d=new n7(a,"",c,void 0);d.hi=null;var e=G7(a),f=a.Hn.clone();g.Cm(f,"RID",c);g.Cm(f,"CVER","1");D7(a,f);yBa(d,f,e);a.Ud=d;a.g=2}}else 3==a.g&&(b?SBa(a,b):0==a.l.length||a.Ud||SBa(a))},SBa=function(a,b){if(b)if(6<a.Th){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Kl-1;var d=G7(a)}else c=b.D,d=b.Gi;else c=a.Kl++,d=G7(a);var e=a.Hn.clone();g.Cm(e,"SID",a.o);g.Cm(e,"RID",c);g.Cm(e,"AID",a.Oj);D7(a,e);c=new n7(a,a.o,c,a.mj+1);c.hi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ud=c;yBa(c,e,d)},D7=function(a,b){if(a.od){var c=a.od.iy();
c&&g.Hb(c,function(a,c){g.Cm(b,c,a)})}},G7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Th&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Th?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},UBa=function(a){a.wc||a.ng||(a.D=1,a.ng=w7((0,g.A)(a.qC,a),0),a.Zi=0)},H7=function(a){if(a.wc||a.ng||3<=a.Zi)return!1;
a.D++;a.ng=w7((0,g.A)(a.qC,a),VBa(a,a.Zi));a.Zi++;return!0},A7=function(a,b,c){a.Qp=c;
a.Kf=b.yg;a.C||QBa(a)},F7=function(a){null!=a.Vh&&(g.x.clearTimeout(a.Vh),a.Vh=null)},VBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},I7=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.A)(a.WU,a);c||(c=new g.tm("//www.google.com/images/cleardot.gif"),Q6(c));FBa(c.toString(),1E4,d)}else r7(2);WBa(a,b)},WBa=function(a,b){a.g=0;
a.od&&a.od.bx(b);OBa(a);NBa(a)},OBa=function(a){a.g=0;
a.Kf=-1;if(a.od)if(0==a.A.length&&0==a.l.length)a.od.Sq();else{g.Va(a.A);var b=g.Va(a.l);a.A.length=0;a.l.length=0;a.od.Sq(b)}},z7=function(a,b,c){var d=g.Dm(c);
if(""!=d.l)b&&g.vm(d,b+"."+d.l),g.wm(d,d.B);else{var e=window.location;d=WAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Rk&&g.Hb(a.Rk,function(a,b){g.Cm(d,b,a)});
g.Cm(d,"VER",a.Th);D7(a,d);return d},w7=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},r7=function(a){J7.dispatchEvent(new KBa(J7,a))},XBa=function(){},YBa=function(a,b){this.action=a;
this.params=b||{}},K7=function(a,b){g.M.call(this);
this.g=new g.Ut(this.bT,0,this);g.N(this,this.g);this.pd=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},L7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.TC;this.l=new K7(this.CV,this);this.g=this.Xa=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},ZBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Qp,sessionId:a.g.o,arrayId:a.g.Oj}},$Ba=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&TBa(a.g),PBa(a.g));a.F=0},M7=function(a){return!!a.g&&3==a.g.g},aCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},N7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Fg(a)||"";b&&(this.port=":"+b);this.domain=g.Eg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.l=!1))},O7=function(a,b){var c=a.g;
if(g.u(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Og(c+b,{})},P7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),ud:g.Ea(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.iE(b,a)},eCa=function(){var a=bCa;
cCa();Q7.push(a);dCa(Q7)},R7=function(a,b){cCa();
var c=Q7,d=fCa(a,String(b));g.Oa(c)?gCa(d):(dCa(c),(0,g.C)(c,function(a){a(d)}))},cCa=function(){Q7||(Q7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",Q7,void 0))},gCa=function(a){var b=(S7+1)%50;
S7=b;T7[b]=a;U7||(U7=49==b)},dCa=function(a){var b=T7;
if(b[0]){var c=S7,d=U7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
T7=Array(50);S7=-1;U7=!1}},fCa=function(a,b){var c=((0,g.G)()-hCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},V7=function(a){g.DF.call(this);
this.D=a;this.g=[]},iCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},jCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Id)(a.g,function(a){return!!Y6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=iCa(a,b[d])||c;return c},kCa=function(a,b){var c=a.g.length;
a.g=(0,g.Id)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},W7=function(a,b,c,d){g.DF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Aa=window.NaN},Y7=function(a){V7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;X7(this);this.info("Initializing with "+W6(this.g))},lCa=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=O7(a.o,"/pairing/get_lounge_token_batch");
P7(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.WI,a),(0,g.A)(a.VI,a))}},X7=function(a){var b=dBa(jBa());
b=(0,g.Id)(b,function(a){return!a.uuid});
return jCa(a,b)},Z7=function(a,b){lBa((0,g.I)(a.g,bBa));
b&&kBa()},a8=function(a,b){g.DF.call(this);
this.C=b;var c=g.KG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;$7("Initialized with "+g.wg(this.g))},mCa=function(a,b,c){var d=O7(a.B,"/pairing/get_screen_availability");
P7(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},b8=function(a,b){a:if(g.Lb(b)!=g.Lb(a.g))var c=!1;
else{c=g.Ob(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||($7("Updated online screens: "+g.wg(a.g)),a.g=b,a.U("screenChange"));nCa(a)},c8=function(a){(0,window.isNaN)(a.o)||g.VD(a.o);
a.o=g.TD((0,g.A)(a.Fu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},$7=function(a){R7("OnlineScreenService",a)},oCa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},nCa=function(a){a=g.Ob(g.Ib(a.g,function(a){return a}));
g.db(a);a.length?g.JG("yt-remote-online-screen-ids",a.join(","),60):g.LG("yt-remote-online-screen-ids")},d8=function(a){V7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};pCa(this)},rCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ie();if(k=(c?Z6(k,c):null)||Z6(k,b)){k.uuid=b;var l=e8(a,k);mCa(a.l,l,function(a){e(a?l:null)})}else c?qCa(a,c,(0,g.A)(function(a){var f=e8(this,new T6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));mCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},sCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},qCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.iE(O7(a.C,"/pairing/get_lounge_token_batch"),e)},tCa=function(a){a.g=a.o.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W6(a.g))},pCa=function(a){f8(a);
a.o=new Y7(a.C);a.o.subscribe("screenChange",(0,g.A)(a.lJ,a));tCa(a);a.A=dBa(g.KG("yt-remote-automatic-screen-cache")||[]);f8(a);a.info("Initializing automatic screens: "+W6(a.A));a.l=new a8(a.C,(0,g.A)(a.ie,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.U("onlineScreenChange")},a))},e8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.JG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,bBa)));f8(a);a.B[b.uuid]=b.id;g.JG("yt-remote-device-id-map",a.B,31536E3);return b},f8=function(a){a.B=g.KG("yt-remote-device-id-map")||{}},g8=function(a,b,c){g.DF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},h8=function(a,b){R7(a.L,b)},i8=function(a,b){g8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.JV,this);this.B=(0,g.A)(this.NT,this);this.A=g.TD((0,g.A)(function(){uCa(this,null)},this),12E4)},vCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.wg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){h8(this,"Failed to send message: getMdxSessionStatus.")},a)):h8(a,"Sending yt message without session: "+g.wg(b))},uCa=function(a,b){g.VD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.Ro,a),d=(0,g.A)(a.oe,a);a.vy(b,c,d,5)}}else a.oe(Error("Waiting for session status timed out."))},j8=function(a,b,c){g8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.z;this.C=window.NaN;this.K=(0,g.A)(this.MV,this);this.g=g.z},wCa=function(a){a.g=a.H.AE(a.I,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.z;
this.Ro(a)},a),(0,g.A)(function(a){this.g=g.z;
this.oe(a)},a))},xCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}nBa()&&(b.env_useStageMdx=1);return g.Mg(b)},k8=function(a,b){g8.call(this,a,b,"ManualSession");
this.g=g.TD((0,g.A)(this.Qj,this,null),150)},l8=function(a,b,c,d){g.DF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.nS,this)},yCa=function(a,b){return b?g.Ja(a.o,function(a){return U6(b,a.label)},a):null},m8=function(a){R7("Controller",a)},bCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},n8=function(a){return a.B||!!a.o.length||!!a.g},o8=function(a,b,c){b!=a.g&&(g.Ye(a.g),(a.g=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.l):a.U("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.oC,a,b)),b.o?a.U("yt-remote-cast2-session-change",b.o):c&&a.g.Qj(null)):a.U("yt-remote-cast2-session-change",null))},zCa=function(a){var b=a.l.zE(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&U6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=yCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},FCa=function(a,b,c,d,e,f,k){ACa()?BCa(b,e,f,k)&&(q8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?CCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?CCa(a,c):(r8("Failed to load cast API: "+d),s8(!1),q8(!1),g.LG("yt-remote-cast-available"),g.LG("yt-remote-cast-receiver"),DCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):qBa():j7("CriOS")?vBa():j7("Android")&&j7("Chrome/")&&window.navigator.presentation?wBa():window.chrome&&window.navigator.presentation&&!j7("Edge")?(k7(),g7(ECa.map(tBa))):h7())):p8("Cannot initialize because not running Chrome")},DCa=function(){p8("dispose");
var a=t8();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);GCa(!1);g.QF(u8);u8.length=0},v8=function(){return!!g.KG("yt-remote-cast-installed")},HCa=function(){var a=g.KG("yt-remote-cast-receiver");
return a?a.friendlyName:null},ICa=function(){p8("clearCurrentReceiver");
g.LG("yt-remote-cast-receiver")},JCa=function(){return v8()?t8()?t8().getCastSession():(r8("getCastSelector: Cast is not initialized."),null):(r8("getCastSelector: Cast API is not installed!"),null)},x8=function(){v8()?t8()?w8()?(p8("Requesting cast selector."),t8().requestSession()):(p8("Wait for cast API to be ready to request the session."),u8.push(g.PF("yt-remote-cast2-api-ready",x8))):r8("requestCastSelector: Cast is not initialized."):r8("requestCastSelector: Cast API is not installed!")},y8=
function(a,b){w8()?t8().setConnectedScreenStatus(a,b):r8("setConnectedScreenStatus called before ready.")},ACa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.tI||a},KCa=function(a,b){t8().init(a,b)},BCa=function(a,b,c,d){var e=!1;
t8()||(a=new l8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.JG("yt-remote-cast-available",a);g.TF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){p8("onReceiverSelected: "+a.friendlyName);
g.JG("yt-remote-cast-receiver",a);g.TF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){p8("onReceiverResumed: "+a.friendlyName);
g.JG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){p8("onSessionChange: "+V6(a));
a||g.LG("yt-remote-cast-receiver");g.TF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
p8("cloudview.createSingleton_: "+e);return e},t8=function(){return g.y("yt.mdx.remote.cloudview.instance_")},CCa=function(a,b){s8(!0);
q8(!1);KCa(a,function(a){a?(GCa(!0),g.SF("yt-remote-cast2-api-ready")):(r8("Failed to initialize cast API."),s8(!1),g.LG("yt-remote-cast-available"),g.LG("yt-remote-cast-receiver"),DCa());b(a)})},p8=function(a){R7("cloudview",a)},r8=function(a){R7("cloudview",a)},s8=function(a){p8("setCastInstalled_ "+a);
g.JG("yt-remote-cast-installed",a)},w8=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},GCa=function(a){p8("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},q8=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},z8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Nf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},A8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Nf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},B8=function(a){return a.jb()?((0,g.G)()-a.D)/1E3:0},C8=function(a,b){a.F=b;
a.D=(0,g.G)()},D8=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},E8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&A8(a)},F8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.l);b.hasPrevious=a.Nf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},H8=function(a,b){g.DF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.jC;this.o=this.l=null;this.H=(0,g.A)(this.JP,this);this.D=(0,g.A)(this.Nl,this);this.F=(0,g.A)(this.IP,this);this.I=(0,g.A)(this.VP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Bv,this),LCa(this))):c=3;0!=c&&(b?this.Bv(c):g.TD((0,g.A)(function(){this.Bv(c)},this),0));
var d=JCa();d&&G8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},I8=function(a){return new z8(a.A.getPlayerContextData())},LCa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.iS,a),this))},a)},MCa=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},J8=function(a,b){50>a.B.Cc()&&g.lC(a.B,b)},L8=function(a,b,c){var d=I8(a);
C8(d,c);-1E3!=d.g&&(d.g=b);K8(a,d)},M8=function(a,b,c){a.A.sendMessage(b,c)},K8=function(a,b){MCa(a);
a.A.setPlayerContextData(F8(b));LCa(a)},G8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Nl(null));
a.o=b;a.o&&(R7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Nl(a.o.media[0]))},NCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=I8(a);b.contentId!=d.videoId&&R7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;C8(d,a.l.getEstimatedTime());K8(a,d)}else R7("CP","No cast media video. Ignoring state update.")},N8=function(a,b,c){return(0,g.A)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),M8(this,b,c))},a)},O8=function(a,b,c){g.DF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.R=[];this.A=this.D=this.o=this.Ya=this.g=null;this.pa=a;this.R.push(g.mF(window,"beforeunload",(0,g.A)(this.LI,this)));this.l=[];this.Ya=new z8;this.Y=b.id;this.g=OCa(this,c);this.g.subscribe("handlerOpened",this.NP,this);this.g.subscribe("handlerClosed",this.KP,this);this.g.subscribe("handlerError",this.LP,this);this.g.subscribe("handlerMessage",this.MP,this);aCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Ya.videoId;g.MG()&&g.JG("yt-remote-session-video-id",a)},this)},P8=function(a){R7("conn",a)},OCa=function(a,b){return new L7(O7(a.pa,"/bc"),b)},Q8=function(a,b){a.U("proxyStateChange",b)},PCa=function(a){a.B=g.TD((0,g.A)(function(){P8("Connecting timeout");
this.C(1)},a),2E4)},R8=function(a){g.VD(a.B);
a.B=window.NaN},S8=function(a){g.VD(a.L);
a.L=window.NaN},QCa=function(a){T8(a);
a.K=g.TD((0,g.A)(function(){U8(this,"getNowPlaying")},a),2E4)},T8=function(a){g.VD(a.K);
a.K=window.NaN},SCa=function(a,b){b&&(R8(a),S8(a));
b==(M7(a.g)&&(0,window.isNaN)(a.B))?b&&(Q8(a,1),U8(a,"getSubtitlesTrack")):b?(a.X()&&a.Ya.reset(),Q8(a,1),U8(a,"getNowPlaying"),RCa(a)):a.C(1)},TCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ya.videoId&&(g.Ub(b.params)?a.Ya.l=null:a.Ya.l=b.params,a.U("remotePlayerChange"))},UCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Ya.listId=b.params.listId||a.Ya.listId;E8(a.Ya,c,d);a.U("remoteQueueChange")},WCa=function(a,b){b.params=b.params||{};
UCa(a,b);VCa(a,b);a.U("autoplayDismissed")},VCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
C8(a.Ya,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Ya.g&&(c=-1E3);a.Ya.g=c;c=Number(b.params.loadedTime);a.Ya.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Ya.H=(0,window.isNaN)(c)?0:c;c=a.Ya;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Ya;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Ya.g?QCa(a):T8(a);
a.U("remotePlayerChange")},XCa=function(a,b){if(-1E3!=a.Ya.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ya.g=c;c=(0,window.parseInt)(b.params.currentTime,10);C8(a.Ya,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},YCa=function(a,b){var c="true"==b.params.muted;
a.Ya.volume=(0,window.parseInt)(b.params.volume,10);a.Ya.muted=c;a.U("remotePlayerChange")},ZCa=function(a,b){a.D=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},$Ca=function(a,b){var c="true"==b.params.hasNext;
a.Ya.Nf="true"==b.params.hasPrevious;a.Ya.hasNext=c;a.U("previousNextChange")},RCa=function(a){g.VD(a.I);
a.I=g.TD((0,g.A)(a.C,a,1),864E5)},U8=function(a,b,c){c?P8("Sending: action="+b+", params="+g.wg(c)):P8("Sending: action="+b);
a.g.sendMessage(b,c)},V8=function(a){V7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.A)(this.HV,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.A)(this.JR,this)))},eDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ND("MDX_CONFIG")||b;fBa();c7();W8||(W8=new N7(b?b.loungeApiHost:void 0),nBa()&&(W8.g="/api/loungedev"));X8||(X8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",X8,void 0));aDa();var c=Y8();if(!c){var d=new d8(W8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=Y8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);FCa(a,d,function(a){a?Z8()&&y8(Z8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.TF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),$8("Initializing: "+g.wg(b)),a9.push(g.PF("yt-remote-cast2-availability-change",function(){g.TF("yt-remote-receiver-availability-change")})),a9.push(g.PF("yt-remote-cast2-receiver-selected",function(){b9(null);
g.TF("yt-remote-auto-connect","cast-selector-receiver")})),a9.push(g.PF("yt-remote-cast2-receiver-resumed",function(){g.TF("yt-remote-receiver-resumed","cast-selector-receiver")})),a9.push(g.PF("yt-remote-cast2-session-change",bDa)),a9.push(g.PF("yt-remote-connection-change",function(a){a?y8(Z8(),"YouTube TV"):c9()||(y8(null,null),ICa())})),a=d9(),b.isAuto&&(a.id+="#dial"),g.JF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),$8(" -- with channel params: "+
g.wg(a)),cDa(a),c.start(),Z8()||dDa())},gDa=function(){var a=fDa();
v8()&&g.KG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},fDa=function(){var a=Y8().dd.$_gos();
var b=e9();b&&f9()&&(Y6(a,b)||a.push(b));return eBa(a)},g9=function(){var a=hDa();
!a&&v8()&&HCa()&&(a={key:"cast-selector-receiver",name:HCa()});return a},hDa=function(){var a=fDa(),b=e9();
b||(b=c9());return g.Ja(a,function(a){return b&&U6(b,a.key)?!0:!1})},e9=function(){var a=Z8();
if(!a)return null;var b=Y8().ie();return Z6(b,a)},bDa=function(a){$8("remote.onCastSessionChange_: "+V6(a));
if(a){var b=e9();b&&b.id==a.id?y8(b.id,"YouTube TV"):(b&&h9(),i9(a,1))}else f9()&&h9()},h9=function(){w8()?t8().stopSession():r8("stopSession called before API ready.");
var a=f9();a&&(a.disconnect(1),j9(null))},k9=function(){var a=f9();
return!!a&&3!=a.getProxyState()},$8=function(a){R7("remote",a)},Y8=function(){if(!l9){var a=g.y("yt.mdx.remote.screenService_");
l9=a?new V8(a):null}return l9},Z8=function(){return g.y("yt.mdx.remote.currentScreenId_")},iDa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},jDa=function(){return g.y("yt.mdx.remote.connectData_")},b9=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},f9=function(){return g.y("yt.mdx.remote.connection_")},j9=function(a){var b=f9();
b9(null);a||iDa("");g.ua("yt.mdx.remote.connection_",a,void 0);X8&&((0,g.C)(X8,function(b){b(a)}),X8.length=0);
b&&!a?g.TF("yt-remote-connection-change",!1):!b&&a&&g.TF("yt-remote-connection-change",!0)},c9=function(){var a=g.MG();
if(!a)return null;var b=Y8().ie();return Z6(b,a)},i9=function(a,b){e9()&&e9();
iDa(a.id);var c=new O8(W8,a,d9());c.connect(b,jDa());c.subscribe("beforeDisconnect",function(a){g.TF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){f9()&&j9(null)});
j9(c)},dDa=function(){var a=c9();
a?($8("Resume connection to: "+V6(a)),i9(a,0)):(d7(),ICa(),$8("Skipping connecting because no session screen found."))},aDa=function(){var a=d9();
if(g.Ub(a)){a=b7();var b=g.KG("yt-remote-session-name")||"",c=g.KG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},d9=function(){return g.y("yt.mdx.remote.channelParams_")||{}},cDa=function(a){a?(g.JG("yt-remote-session-app",a.app),g.JG("yt-remote-session-name",a.name)):(g.LG("yt-remote-session-app"),g.LG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},m9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.AF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.cR);this.o.O(b,"captionschanged",this.HP);this.o.O(b,"captionssettingschanged",this.OD);this.o.O(b,"videoplayerreset",this.So);this.o.O(b,"mdxautoplaycancel",this.SH);this.R=this.o.O(b,"onVolumeChange",this.XB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.lC,this);c.subscribe("remotePlayerChange",this.Ql,this);c.subscribe("remoteQueueChange",this.So,this);c.subscribe("autoplayUpNext",this.HB,
this);c.subscribe("previousNextChange",this.iC,this);c.subscribe("nowAutoplaying",this.aC,this);c.subscribe("autoplayDismissed",this.GB,this);this.suggestion=null;this.H=new g.AP(64);this.A=new g.Ut(this.KD,500,this);g.N(this,this.A);this.B=new g.Ut(this.LD,1E3,this);g.N(this,this.B);this.K=new l7(this.kV,0,this);g.N(this,this.K);this.C={};this.L=new g.Ut(this.lE,1E3,this);g.N(this,this.L);this.I=new g.Uk(this.GN,1E3,this);g.N(this,this.I);this.N=g.z;this.OD();this.So();this.Ql()},n9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},kDa=function(a){n9(a,0);
a.A.stop();o9(a,new g.AP(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.l.zi()},g.bc(c,b));a.g.zD(a.l.getVideoData(1).videoId,c);a.C=I8(a.g).l}},r9=function(a,b){var c=a.l.Xf();
if(c){var d=c.ge();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Jj;f=VAa(f);var n=I8(c);l=l||0;var q={videoId:k,currentIndex:l};E8(n,k,l);g.u(b)&&(C8(n,b),q.currentTime=b);g.u(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.wg(f));M8(c,"setPlaylist",q);e||K8(c,n);o9(a,new g.AP(1))},lDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{nz:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.Tj("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},p9=function(a){return I8(a.g).videoId==a.l.getVideoData(1).videoId},o9=function(a,b){a.B.stop();
var c=a.H;if(!g.FP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.iV(a.l,d);a.H=b;mDa(a.F,c,b)}},s9=function(a){g.W.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.Noa()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.o=new g.YV(this,250);g.N(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);nDa(this,g.fV(a))},nDa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},t9=function(a,b){g.f_.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.K);this.O(a,"presentingplayerstatechange",this.K);this.K()},u9=function(a){g.DV.call(this,a);
g.OG({YTP_MDX_CAST_SELECTOR:"Yay\u0131nla...",YTP_MDX_MY_COMPUTER:"Bu bilgisayar",YTP_MDX_PLAYER_ERROR:"Bu video uzaktan oynatma i\u00e7in uygun de\u011fil.",YTP_MDX_STATUS_CONNECTED_2:"$RECEIVER_NAME cihaz\u0131na ba\u011flan\u0131ld\u0131",YTP_MDX_STATUS_ERROR_2:"$RECEIVER_NAME cihaz\u0131nda hata olu\u015ftu",YTP_MDX_STATUS_PLAYING_2:"$RECEIVER_NAME cihaz\u0131nda oynat\u0131l\u0131yor",YTP_MDX_TITLE:"Oynat\u0131lacak ekran se\u00e7in"});this.o={key:X6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=
null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.AP(64);this.H=0;if(!g.RM(g.Y(this.g))){a=this.g;var b=g.AH(a);b&&(b=b.wo())&&(b=new t9(a,b),g.N(this,b));b=new s9(a);g.N(this,b);g.xV(a,b.element,4)}},mDa=function(a,b,c){a.D=c;
a.g.U("presentingplayerstatechange",new g.KP(c,b))},v9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)h9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Jj,index:Math.max(a.g.pA(),0),currentTime:0==f?void 0:f};(d=VAa(d))&&(c.locationInfo=d);d=c}else d=null;$8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(b9(d||null),w8()?t8().setLaunchParams(d||null):
r8("setLaunchParams called before ready.")):!d&&k9()&&Z8()==b.key?g.TF("yt-remote-connection-change",!0):(h9(),b9(d||null),d=Y8().ie(),(d=Z6(d,b.key))&&i9(d,1))}},CBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},v7={"'":"\\'"},oDa={},aBa={YW:"atp",u1:"ska",J0:"que",W_:"mus",p1:"sus",gZ:"dsp"};
S6.prototype.pn=function(){var a=new S6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var e7,a7="",i7=f7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",uBa=f7("loadCastFramework")||f7("loadCastApplicationFramework"),ECa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(l7,g.M);g.h=l7.prototype;g.h.GI=function(a){this.A=arguments;this.g=!1;this.Aa?this.o=(0,g.G)()+this.pd:this.Aa=g.qg(this.B,this.pd)};
g.h.stop=function(){this.Aa&&(g.rg(this.Aa),this.Aa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();l7.ba.V.call(this)};
g.h.HI=function(){this.o?(this.Aa=g.qg(this.B,this.o-(0,g.G)()),this.o=null):(this.Aa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};m7.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
m7.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=n7.prototype;g.h.hi=null;g.h.zf=!1;g.h.Ak=null;g.h.tv=null;g.h.ik=null;g.h.Aj=null;g.h.eh=null;g.h.Ch=null;g.h.Gi=null;g.h.Qc=null;g.h.pm=0;g.h.Af=null;g.h.Rp=null;g.h.fh=null;g.h.il=-1;g.h.gD=!0;g.h.Rh=!1;g.h.Nr=0;g.h.fp=null;var ABa={},q7={};g.h=n7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.eU=function(a){a=a.target;var b=this.fp;b&&3==g.ex(a)?b.yj():this.tE(a)};
g.h.tE=function(a){try{if(a==this.Qc)a:{var b=g.ex(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.vd&&!g.oc(10)||g.xd&&!g.nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bf&&!g.ix(this.Qc))break a;this.Rh||4!=b||7==c||(8==c||0>=d?this.g.tf(3):this.g.tf(2));x7(this);var e=this.Qc.getStatus();this.il=e;var f=g.ix(this.Qc);(this.zf=200==e)?(4==b&&t7(this),this.B?(BBa(this,b,f),g.bf&&this.zf&&3==b&&(this.W.T(this.l,"tick",this.aU),this.l.start())):s7(this,f),this.zf&&!this.Rh&&(4==b?this.g.Qo(this):
(this.zf=!1,p7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.fh=3,r7(13)):(this.fh=0,r7(14)),t7(this),u7(this))}}catch(k){this.Qc&&g.ix(this.Qc)}finally{}};
g.h.aU=function(){var a=g.ex(this.Qc),b=g.ix(this.Qc);this.pm<b.length&&(x7(this),BBa(this,a,b),this.zf&&4!=a&&p7(this))};
g.h.kT=function(a){w7((0,g.A)(this.jT,this,a),0)};
g.h.jT=function(a){this.Rh||(x7(this),s7(this,a),p7(this))};
g.h.tC=function(a){w7((0,g.A)(this.iT,this,a),0)};
g.h.iT=function(a){this.Rh||(t7(this),this.zf=a,this.g.Qo(this),this.g.tf(4))};
g.h.cancel=function(){this.Rh=!0;t7(this)};
g.h.AT=function(){this.Ak=null;var a=(0,g.G)();0<=a-this.tv?(2!=this.Aj&&this.g.tf(3),t7(this),this.fh=2,r7(18),u7(this)):EBa(this,this.tv-a)};g.h=HBa.prototype;g.h.Lr=null;g.h.pe=null;g.h.gp=!1;g.h.Ey=null;g.h.Dn=null;g.h.Ps=null;g.h.Mr=null;g.h.Ke=null;g.h.yg=-1;g.h.fl=null;g.h.Gk=null;g.h.connect=function(a){this.Mr=a;a=z7(this.g,null,this.Mr);r7(3);this.Ey=(0,g.G)();var b=this.g.F;null!=b?(this.fl=b[0],(this.Gk=b[1])?(this.Ke=1,IBa(this)):(this.Ke=2,B7(this))):(R6(a,"MODE","init"),this.pe=new n7(this,void 0,void 0,void 0),this.pe.hi=this.Lr,o7(this.pe,a,!1,null,!0),this.Ke=0)};
g.h.TH=function(a){if(a)this.Ke=2,B7(this);else{r7(4);var b=this.g;b.Kf=b.Vg.yg;I7(b,9)}a&&this.tf(2)};
g.h.ir=function(a){return this.g.ir(a)};
g.h.abort=function(){this.pe&&(this.pe.cancel(),this.pe=null);this.yg=-1};
g.h.Dy=function(){return!1};
g.h.mC=function(a,b){this.yg=a.il;if(0==this.Ke)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Kf=this.yg;I7(c,2);return}this.fl=c[0];this.Gk=c[1]}else c=this.g,c.Kf=this.yg,I7(c,2);else if(2==this.Ke)if(this.gp)r7(7),this.Ps=(0,g.G)();else if("11111"==b){if(r7(6),this.gp=!0,this.Dn=(0,g.G)(),c=this.Dn-this.Ey,!g.vd||g.oc(10)||500>c)this.yg=200,this.pe.cancel(),r7(12),A7(this.g,this,!0)}else r7(8),this.Dn=this.Ps=(0,g.G)(),this.gp=!1};
g.h.Qo=function(){this.yg=this.pe.il;if(this.pe.zf)0==this.Ke?this.Gk?(this.Ke=1,IBa(this)):(this.Ke=2,B7(this)):2==this.Ke&&((!g.vd||g.oc(10)?!this.gp:200>this.Ps-this.Dn)?(r7(11),A7(this.g,this,!1)):(r7(12),A7(this.g,this,!0)));else{0==this.Ke?r7(9):2==this.Ke&&r7(10);var a=this.g;a.Kf=this.yg;I7(a,2)}};
g.h.dm=function(){return this.g.dm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.tf=function(a){this.g.tf(a)};g.h=C7.prototype;g.h.Rk=null;g.h.Ud=null;g.h.wc=null;g.h.Kr=null;g.h.Hn=null;g.h.Sw=null;g.h.Sn=null;g.h.Kl=0;g.h.ZO=0;g.h.od=null;g.h.Xg=null;g.h.ng=null;g.h.Vh=null;g.h.Vg=null;g.h.Qp=null;g.h.Oj=-1;g.h.Dz=-1;g.h.Kf=-1;g.h.mj=0;g.h.Zi=0;g.h.Th=8;var J7=new g.Bf;g.B(KBa,g.$e);g.B(LBa,g.$e);g.B(MBa,g.$e);g.h=C7.prototype;g.h.connect=function(a,b,c,d,e){r7(0);this.Kr=b;this.Rk=c||{};d&&g.u(e)&&(this.Rk.OSID=d,this.Rk.OAID=e);this.C?(w7((0,g.A)(this.rx,this,a),100),QBa(this)):this.rx(a)};
g.h.rx=function(a){this.Vg=new HBa(this);this.Vg.Lr=null;this.Vg.l=this.B;this.Vg.connect(a)};
g.h.Dy=function(){return 0==this.g};
g.h.rC=function(a){this.Xg=null;TBa(this,a)};
g.h.qC=function(){this.ng=null;this.wc=new n7(this,this.o,"rpc",this.D);this.wc.hi=null;this.wc.Nr=0;var a=this.Sw.clone();g.Cm(a,"RID","rpc");g.Cm(a,"SID",this.o);g.Cm(a,"CI",this.Qp?"0":"1");g.Cm(a,"AID",this.Oj);D7(this,a);if(!g.vd||g.oc(10))g.Cm(a,"TYPE","xmlhttp"),o7(this.wc,a,!0,this.Sn,!1);else{g.Cm(a,"TYPE","html");var b=this.wc,c=!!this.Sn;b.Aj=3;b.eh=Q6(a.clone());DBa(b,c)}};
g.h.mC=function(a,b){if(0!=this.g&&(this.wc==a||this.Ud==a))if(this.Kf=a.il,this.Ud==a&&3==this.g)if(7<this.Th){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.ng){if(this.wc)if(this.wc.ik+3E3<this.Ud.ik)F7(this),this.wc.cancel(),this.wc=null;else break a;H7(this);r7(19)}}else this.Dz=c[1],0<this.Dz-this.Oj&&37500>c[2]&&this.Qp&&0==this.Zi&&!this.Vh&&(this.Vh=w7((0,g.A)(this.CP,this),6E3));else I7(this,11)}else b!=oDa.bY.g&&I7(this,11);else if(this.wc==a&&
F7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Oj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Sn=e[2],e=e[3],null!=e?this.Th=e:this.Th=6,this.g=3,this.od&&this.od.gx(),this.Sw=z7(this,this.dm()?this.Sn:null,this.Kr),UBa(this)):"stop"==e[0]&&I7(this,7):3==this.g&&("stop"==e[0]?I7(this,7):"noop"!=e[0]&&this.od&&this.od.fx(e),this.Zi=0)}}};
g.h.CP=function(){null!=this.Vh&&(this.Vh=null,this.wc.cancel(),this.wc=null,H7(this),r7(20))};
g.h.Qo=function(a){if(this.wc==a){F7(this);this.wc=null;var b=2}else if(this.Ud==a)this.Ud=null,b=1;else return;this.Kf=a.il;if(0!=this.g)if(a.zf)1==b?(b=(0,g.G)()-a.ik,J7.dispatchEvent(new LBa(J7,a.Gi?a.Gi.length:0,b,this.mj)),E7(this),this.A.length=0):UBa(this);else{var c=a.fh,d;if(!(d=3==c||7==c||0==c&&0<this.Kf)){if(d=1==b)this.Ud||this.Xg||1==this.g||2<=this.mj?d=!1:(this.Xg=w7((0,g.A)(this.rC,this,a),VBa(this,this.mj)),this.mj++,d=!0);d=!(d||2==b&&H7(this))}if(d)switch(c){case 1:I7(this,5);
break;case 4:I7(this,10);break;case 3:I7(this,6);break;case 7:I7(this,12);break;default:I7(this,2)}}};
g.h.pI=function(a){if(!g.Na(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.WU=function(a){a?r7(2):(r7(1),WBa(this,8))};
g.h.ir=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Zw;a.F=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.tf=function(a){J7.dispatchEvent(new MBa(J7,a))};
g.h.dm=function(){return!(!g.vd||g.oc(10))};
g.h=XBa.prototype;g.h.gx=function(){};
g.h.fx=function(){};
g.h.bx=function(){};
g.h.Sq=function(){};
g.h.iy=function(){return{}};
g.h.isActive=function(){return!0};g.B(K7,g.M);g.h=K7.prototype;g.h.bT=function(){this.pd=Math.min(3E5,2*this.pd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.pd+15E3*Math.random();g.Vt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.pd=5E3};g.B(L7,XBa);g.h=L7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Nd=function(a){return this.o.Nd(a)};
g.h.U=function(a,b){return this.o.U.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ye(this.o),$Ba(this),g.Ye(this.l),this.l=null)};
g.h.ia=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new C7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.od=null);d.od=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Oj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):M7(this)&&RBa(this.g,c)};
g.h.gx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)RBa(this.g,a[b])}this.U("handlerOpened")};
g.h.bx=function(a){var b=2==a&&401==this.g.Kf;4==a||b||this.l.start();this.U("handlerError",a)};
g.h.Sq=function(a){if(!this.l.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.iy=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.bc(a,this.B);return a};
g.h.fx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),PBa(this.g)):this.U("handlerMessage",new YBa(a[0],a[1]))};
g.h.CV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Ud&&b++;0!=b||this.connect(this.B,this.A)};N7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
N7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
N7.prototype.B=function(a){a(Error("request timed out"))};var hCa=(0,g.G)(),Q7=null,T7=Array(50),S7=-1,U7=!1;g.B(V7,g.DF);V7.prototype.ie=function(){return this.g};
V7.prototype.contains=function(a){return!!Y6(this.g,a)};
V7.prototype.get=function(a){return a?Z6(this.g,a):null};
V7.prototype.info=function(a){R7(this.D,a)};g.B(W7,g.DF);var pDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=W7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.yE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.VD(this.Aa),this.Aa=window.NaN)};
g.h.V=function(){this.stop();W7.ba.V.call(this)};
g.h.yE=function(){this.Aa=window.NaN;this.g=g.iE(O7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.FV,this),onError:(0,g.A)(this.EV,this),ud:(0,g.A)(this.GV,this)})};
g.h.FV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.U("pairingComplete",new T6(c))};
g.h.EV=function(a){this.g=null;a.status&&404==a.status?this.l>=pDa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=pDa[this.l],this.Aa=g.TD((0,g.A)(this.yE,this),a),this.l++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.GV=function(){this.g=null;this.U("pairingFailed",Error("Server not responding"))};g.B(Y7,V7);g.h=Y7.prototype;g.h.start=function(){X7(this)&&this.U("screenChange");!g.KG("yt-remote-lounge-token-expiration")&&lCa(this);g.VD(this.l);this.l=g.TD((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){X7(this);iCa(this,a);Z7(this,!1);this.U("screenChange");b(a);a.token||lCa(this)};
g.h.remove=function(a,b){var c=X7(this);kCa(this,a)&&(Z7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.Lp=function(a,b,c,d){var e=X7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Z7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.V=function(){g.VD(this.l);Y7.ba.V.call(this)};
g.h.WI=function(a){X7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Z7(this,!b);b&&R7(this.D,"Missed "+b+" lounge tokens.")};
g.h.VI=function(a){R7(this.D,"Requesting lounge tokens failed: "+a)};g.B(a8,g.DF);g.h=a8.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.KG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?c8(this):(this.A=(0,g.G)()+3E5,g.JG("yt-remote-fast-check-period",this.A),this.Fu())};
g.h.isEmpty=function(){return g.Ub(this.g)};
g.h.update=function(){$7("Updating availability on schedule.");var a=this.C(),b=g.Ib(this.g,function(b,d){return b&&!!Z6(a,d)},this);
b8(this,b)};
g.h.V=function(){g.VD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);a8.ba.V.call(this)};
g.h.Fu=function(){g.VD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=oCa(this);if(g.Lb(a)){var b=O7(this.B,"/pairing/get_screen_availability");this.l=P7(this.B,b,{lounge_token:g.Ob(a).join(",")},(0,g.A)(this.HS,this,a),(0,g.A)(this.GS,this))}else b8(this,{}),c8(this)};
g.h.HS=function(a,b){this.l=null;var c=g.Ob(oCa(this));if(g.eb(c,g.Ob(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;b8(this,d);c8(this)}else this.gc("Changing Screen set during request."),this.Fu()};
g.h.GS=function(a){this.gc("Screen availability failed: "+a);this.l=null;c8(this)};
g.h.gc=function(a){R7("OnlineScreenService",a)};g.B(d8,V7);g.h=d8.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.U("screenChange"),this.l.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Lp=function(a,b,c,d){this.o.contains(a)?this.o.Lp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,R7(this.D,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Ua(this.g,(0,g.Id)(this.A,function(a){return!this.contains(a)},this))};
g.h.zE=function(){return(0,g.Id)(this.ie(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.AE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new W7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ye(f);d(e8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ye(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.IV=function(a,b,c,d){g.iE(O7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new T6(d.screen||{});if(!e.name||sCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);sCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(e8(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ye(this.o);g.Ye(this.l);d8.ba.V.call(this)};
g.h.lJ=function(){tCa(this);this.U("screenChange");this.l.update()};
d8.prototype.dispose=d8.prototype.dispose;g.B(g8,g.DF);g.h=g8.prototype;g.h.Ro=function(a){this.o=a;this.U("sessionScreen",this.o)};
g.h.oe=function(a){this.ia()||(a&&h8(this,""+a),this.o=null,this.U("sessionScreen",null))};
g.h.info=function(a){R7(this.L,a)};
g.h.CE=function(){return null};
g.h.Mu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){h8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Mu("");g8.ba.V.call(this)};g.B(i8,g8);g.h=i8.prototype;g.h.Lu=function(a){if(this.g){if(this.g==a)return;h8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);vCa(this)};
g.h.Qj=function(a){this.info("launchWithParams no-op for Cast: "+g.wg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.oe()},this),(0,g.A)(function(){this.oe(Error("Failed to stop receiver app."))},this)):this.oe(Error("Stopping cast device witout session."))};
g.h.Mu=g.z;g.h.V=function(){this.info("disposeInternal");g.VD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;i8.ba.V.call(this)};
g.h.NT=function(a,b){if(!this.ia())if(b){var c=g.Tw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.wg(c));switch(d){case "mdxSessionStatus":uCa(this,c.screenId);break;default:h8(this,"Unknown youtube message: "+d)}}else h8(this,"Unable to parse message.")}else h8(this,"No data in message.")};
g.h.vy=function(a,b,c,d){rCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(h8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.TD((0,g.A)(this.vy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.CE=function(){return this.g};
g.h.JV=function(a){this.ia()||a||(h8(this,"Cast session died."),this.oe())};g.B(j8,g8);g.h=j8.prototype;g.h.Lu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Qj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.z;g.VD(this.C);this.A?this.A.stop((0,g.A)(this.oe,this,null),(0,g.A)(this.oe,this,"Failed to stop DIAL device.")):this.oe()};
g.h.V=function(){this.g();this.g=g.z;g.VD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;j8.ba.V.call(this)};
g.h.MV=function(a){this.ia()||a||(h8(this,"DIAL session died."),this.g(),this.g=g.z,this.oe())};
g.h.Bs=function(a){this.I=X6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,xCa(this));a(b);wCa(this)}else this.D=(0,g.A)(function(){g.VD(this.C);this.D=g.z;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,xCa(this));a(b);wCa(this)},this),this.C=g.TD((0,g.A)(function(){this.D()},this),100)};
g.h.zK=function(a,b,c){rCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Ro(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Bs(b,c)},this),(0,g.A)(function(a){h8(this,"Failed to get DIAL screen: "+a);
this.Bs(b,c)},this))};g.B(k8,g8);k8.prototype.stop=function(){this.oe()};
k8.prototype.Lu=g.z;k8.prototype.Qj=function(){g.VD(this.g);this.g=window.NaN;var a=Z6(this.H.ie(),this.l.label);a?this.Ro(a):this.oe(Error("No such screen"))};
k8.prototype.V=function(){g.VD(this.g);this.g=window.NaN;k8.ba.V.call(this)};g.B(l8,g.DF);g.h=l8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.nC,this),(0,g.A)(this.rS,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.mQ,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.A),eCa(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.BE,this)),this.o=zCa(this),window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.wg(a))},this)),this.U("yt-remote-cast2-availability-change",n8(this)),b(!0))},this),(0,g.A)(function(a){this.gc("Failed to initialize API: "+g.wg(a));
b(!1)},this))};
g.h.GU=function(a,b){m8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)m8("Unsetting old screen status: "+this.g.l.friendlyName),o8(this,null)}if(a&&b){if(!this.g){c=Z6(this.l.ie(),a);if(!c){m8("setConnectedScreenStatus: Unknown screen.");return}var d=yCa(this,c);d||(m8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.wg(a))},this)));
m8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);o8(this,new k8(this.l,d),!0)}this.g.Mu(b)}else m8("setConnectedScreenStatus: no screen.")};
g.h.HU=function(a){this.ia()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Qj(a):this.gc("Setting connection data without a session")};
g.h.LV=function(){this.ia()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),o8(this,null)):m8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.nC,this),(0,g.A)(this.MS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.BE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],bCa);g.Ye(this.g);l8.ba.V.call(this)};
g.h.gc=function(a){R7("Controller",a)};
g.h.oC=function(a,b){this.g==a&&(b||o8(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.nS=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),m8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)m8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{m8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.U("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:o8(this,
new k8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:o8(this,new j8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:o8(this,new i8(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.mQ=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return m8("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);o8(this,new j8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.zK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Bs,b))};
g.h.nC=function(a){if(!this.ia()){m8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)m8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),o8(this,new i8(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=Z6(this.l.ie(),c.label);
d&&U6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(m8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ye(this.g),this.g=new i8(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.oC,this,this.g)),this.g.Qj(null));this.g.Lu(a)}}};
g.h.KV=function(){return this.g?this.g.CE():null};
g.h.MS=function(a){this.ia()||(this.gc("Failed to estabilish a session: "+g.wg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&o8(this,null))};
g.h.rS=function(a){m8("Receiver availability updated: "+a);if(!this.ia()){var b=n8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;n8(this)!=b&&this.U("yt-remote-cast2-availability-change",n8(this))}};
g.h.BE=function(){this.ia()||(this.o=zCa(this),m8("Updating custom receivers: "+g.wg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(){this.gc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",n8(this)))};
l8.prototype.setLaunchParams=l8.prototype.HU;l8.prototype.setConnectedScreenStatus=l8.prototype.GU;l8.prototype.stopSession=l8.prototype.LV;l8.prototype.getCastSession=l8.prototype.KV;l8.prototype.requestSession=l8.prototype.requestSession;l8.prototype.init=l8.prototype.init;l8.prototype.dispose=l8.prototype.dispose;var u8=[];g.h=z8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";A8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Nf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.jb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+B8(this):this.H};
g.h.clone=function(){return new z8(F8(this))};g.B(H8,g.DF);g.h=H8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.z,N8(this,"play")):M8(this,"play"),L8(this,1,D8(I8(this))),this.U("remotePlayerChange")):J8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.z,N8(this,"pause")):M8(this,"pause"),L8(this,2,D8(I8(this))),this.U("remotePlayerChange")):J8(this,this.pause)};
g.h.xE=function(a){if(1==this.g){if(this.l){var b=I8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.z,N8(this,"seekTo",{newTime:a}))}else M8(this,"seekTo",{newTime:a});L8(this,3,a);this.U("remotePlayerChange")}else J8(this,g.Ea(this.xE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.z,N8(this,"stopVideo")):M8(this,"stopVideo");var a=I8(this);a.index=-1;a.videoId="";A8(a);K8(this,a);this.U("remotePlayerChange")}else J8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=I8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){R7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){R7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);M8(this,"setVolume",e)}c.muted=b;c.volume=a;K8(this,c)}else J8(this,g.Ea(this.setVolume,a,b))};
g.h.zD=function(a,b){if(1==this.g){var c=I8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.bc(d,c.l));M8(this,"setSubtitlesTrack",d);K8(this,c)}else J8(this,g.Ea(this.zD,a,b))};
g.h.Av=function(a,b){if(1==this.g){M8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Gb.id});var c=I8(this);c.audioTrackId=b.Gb.id;K8(this,c)}else J8(this,g.Ea(this.Av,a,b))};
g.h.wE=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"previous")}else J8(this,g.Ea(this.wE,a,b))};
g.h.vE=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"next")}else J8(this,g.Ea(this.vE,a,b))};
g.h.Kx=function(){1==this.g?M8(this,"dismissAutoplay"):J8(this,this.Kx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}H8.ba.dispose.call(this)};
g.h.V=function(){MCa(this);this.A=null;this.B.clear();G8(this,null);H8.ba.V.call(this)};
g.h.Bv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.mC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.iS=function(a,b){this.U(a,b)};
g.h.JP=function(a){if(!a)this.Nl(null),G8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=I8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)R7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,K8(this,b)}};
g.h.Nl=function(a){R7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),NCa(this),this.U("remotePlayerChange")};
g.h.IP=function(a){a?(NCa(this),this.U("remotePlayerChange")):this.Nl(null)};
g.h.VP=function(){var a=JCa();a&&G8(this,a)};
g.h.gc=function(a){R7("CP",a)};g.B(O8,g.DF);g.h=O8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.Ya.listId=c);this.Ya.videoId=d;this.Ya.index=k||0;this.Ya.state=3;C8(this.Ya,m);this.A="UNSUPPORTED";P8("Connecting with setPlaylist and params: "+g.wg(l));this.g.connect({method:"setPlaylist",
params:g.wg(l)},a,iBa())}else P8("Connecting without params"),this.g.connect({},a,iBa());PCa(this)};
g.h.dispose=function(){this.ia()||(this.U("beforeDispose"),Q8(this,3));O8.ba.dispose.call(this)};
g.h.V=function(){R8(this);T8(this);S8(this);g.VD(this.H);this.H=window.NaN;g.VD(this.I);this.I=window.NaN;this.o=null;g.nF(this.R);this.R.length=0;this.g.dispose();O8.ba.V.call(this);this.A=this.D=this.l=this.Ya=this.g=null};
g.h.LI=function(){this.C(2)};
g.h.NP=function(){P8("Channel opened");this.N&&(this.N=!1,S8(this),this.L=g.TD((0,g.A)(function(){P8("Timing out waiting for a screen.");this.C(1)},this),15E3));
mBa(ZBa(this.g),this.Y)};
g.h.KP=function(){P8("Channel closed");(0,window.isNaN)(this.B)?d7(!0):d7();this.dispose()};
g.h.LP=function(a){d7();(0,window.isNaN)(this.F())?(P8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,P8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Q8(this,2))};
g.h.MP=function(a){a.params?P8("Received: action="+a.action+", params="+g.wg(a.params)):P8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Tw(a.params.devices);this.l=(0,g.I)(a,function(a){return new S6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
SCa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
SCa(this,!1);break;case "remoteConnected":var b=new S6(g.Tw(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new S6(g.Tw(a.params.device));g.Ta(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":UCa(this,a);break;case "nowPlaying":WCa(this,a);break;case "onStateChange":VCa(this,a);break;case "onAdStateChange":XCa(this,a);break;case "onVolumeChanged":YCa(this,a);break;case "onSubtitlesTrackChanged":TCa(this,a);break;case "nowAutoplaying":ZCa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.U("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.U("autoplayModeChange",this.A);"DISABLED"==this.A&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":$Ca(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:P8("Unrecognized action: "+a.action)}};
g.h.qU=function(){if(this.o){var a=this.o;this.o=null;this.Ya.videoId!=a&&U8(this,"getNowPlaying")}};
O8.prototype.subscribe=O8.prototype.subscribe;O8.prototype.unsubscribeByKey=O8.prototype.Nd;O8.prototype.fa=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.F())?M7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
O8.prototype.getProxyState=O8.prototype.fa;O8.prototype.C=function(a){P8("Disconnecting with "+a);R8(this);this.U("beforeDisconnect",a);1==a&&d7();$Ba(this.g,a);this.dispose()};
O8.prototype.disconnect=O8.prototype.C;O8.prototype.ea=function(){var a=this.Ya;this.o&&(a=this.Ya.clone(),E8(a,this.o,a.index));return F8(a)};
O8.prototype.getPlayerContextData=O8.prototype.ea;
O8.prototype.ma=function(a){var b=new z8(a);b.videoId&&b.videoId!=this.Ya.videoId&&(this.o=b.videoId,g.VD(this.H),this.H=g.TD((0,g.A)(this.qU,this),5E3));var c=[];this.Ya.listId==b.listId&&this.Ya.videoId==b.videoId&&this.Ya.index==b.index||c.push("remoteQueueChange");this.Ya.g==b.g&&this.Ya.volume==b.volume&&this.Ya.muted==b.muted&&D8(this.Ya)==D8(b)&&g.wg(this.Ya.l)==g.wg(b.l)||c.push("remotePlayerChange");this.Ya.reset(a);(0,g.C)(c,function(a){this.U(a)},this)};
O8.prototype.setPlayerContextData=O8.prototype.ma;O8.prototype.X=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
O8.prototype.getOtherConnectedRemoteId=O8.prototype.X;O8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
O8.prototype.getReconnectTimeout=O8.prototype.F;O8.prototype.Z=function(){return this.A||"UNSUPPORTED"};
O8.prototype.getAutoplayMode=O8.prototype.Z;O8.prototype.aa=function(){return this.D||""};
O8.prototype.getAutoplayVideoId=O8.prototype.aa;O8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Wt(a.g);a.start()}};
O8.prototype.reconnect=O8.prototype.ra;O8.prototype.ha=function(a,b){U8(this,a,b);RCa(this)};
O8.prototype.sendMessage=O8.prototype.ha;g.B(V8,V7);g.h=V8.prototype;g.h.ie=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Lp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;V8.ba.V.call(this)};
g.h.HV=function(){this.U("screenChange")};
g.h.JR=function(){this.U("onlineScreenChange")};
d8.prototype.$_st=d8.prototype.start;d8.prototype.$_gspc=d8.prototype.IV;d8.prototype.$_gsppc=d8.prototype.AE;d8.prototype.$_c=d8.prototype.contains;d8.prototype.$_g=d8.prototype.get;d8.prototype.$_a=d8.prototype.add;d8.prototype.$_un=d8.prototype.Lp;d8.prototype.$_r=d8.prototype.remove;d8.prototype.$_gs=d8.prototype.ie;d8.prototype.$_gos=d8.prototype.zE;d8.prototype.$_s=d8.prototype.subscribe;d8.prototype.$_ubk=d8.prototype.Nd;var W8=null,X8=null,l9=null,a9=[];g.t(m9,g.M);g.h=m9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.lC,this);this.g.unsubscribe("remotePlayerChange",this.Ql,this);this.g.unsubscribe("remoteQueueChange",this.So,this);this.g.unsubscribe("autoplayUpNext",this.HB,this);this.g.unsubscribe("previousNextChange",this.iC,this);this.g.unsubscribe("nowAutoplaying",this.aC,this);this.g.unsubscribe("autoplayDismissed",this.GB,this);this.g=this.F=null};
g.h.JA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(!I8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":I8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.yj(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.Av(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();r9(this,0==c?void 0:c);break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.Av(this.l.getVideoData(1).videoId,c)}};
g.h.HP=function(a){this.K.GI(a)};
g.h.kV=function(a){this.JA("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.OD=function(){var a=this.l.xc("captions","track");g.Ub(a)||q9(this,a)};
g.h.XB=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.Ql,this);var b=Math.round(a.volume);a=!!a.muted;var c=I8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Ql,this)}};
g.h.cR=function(){g.Ub(this.C)||lDa(this,this.C);this.D=!1};
g.h.lC=function(a,b){this.B.stop();2==b&&this.LD()};
g.h.Ql=function(){if(p9(this)){this.A.stop();var a=I8(this.g);switch(a.g){case 1081:case 1:o9(this,new g.AP(8));this.KD();break;case 1085:case 3:o9(this,new g.AP(9));break;case 1083:case 0:o9(this,new g.AP(2));this.I.stop();n9(this,this.l.getVideoData().lengthSeconds);break;case 1084:o9(this,new g.AP(4));break;case 2:o9(this,new g.AP(4));n9(this,D8(a));break;case -1:o9(this,new g.AP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},o9(this,new g.AP(128,a))}a=
I8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,lDa(this,a));a=I8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.lE()}else kDa(this)};
g.h.iC=function(){this.l.U("mdxpreviousnextchange")};
g.h.So=function(){p9(this)||kDa(this)};
g.h.SH=function(){this.g.Kx()};
g.h.HB=function(a){a&&(a=g.iE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.nT,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.nT=function(a,b){var c=new g.pO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.U("mdxautoplayupnext",c)};
g.h.aC=function(a){(0,window.isNaN)(a)||this.l.U("mdxnowautoplaying",a)};
g.h.GB=function(){this.l.U("mdxautoplaycanceled")};
g.h.GN=function(a,b){-1==I8(this.g).g?r9(this,a):b&&this.g.xE(a)};
g.h.lE=function(){if(p9(this)){var a=I8(this.g);this.o.Ca(this.R);a.muted?this.l.mute():this.l.Yf();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.XB)}};
g.h.KD=function(){this.A.stop();if(!this.g.ia()){var a=I8(this.g);a.jb()&&o9(this,new g.AP(8));n9(this,D8(a));this.A.start()}};
g.h.LD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.t(s9,g.W);s9.prototype.B=function(a){nDa(this,a.state)};g.t(t9,g.f_);t9.prototype.K=function(){var a=this.o.xc("remote","receivers");a&&1<a.length&&!this.o.xc("remote","quickCast")?(this.H=g.gb(a,this.C,this),g.g_(this,(0,g.I)(a,this.C)),a=this.o.xc("remote","currentReceiver"),this.sf(this.C(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.C=function(a){return a.key};
t9.prototype.rf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.H[a].name};
t9.prototype.sd=function(a){g.f_.prototype.sd.call(this,a);this.o.Jd("remote","currentReceiver",this.H[a]);this.B.Pb()};g.t(u9,g.DV);g.h=u9.prototype;g.h.create=function(){eDa(g.EM(g.Y(this.g)));this.C.push(g.PF("yt-remote-before-disconnect",this.DP,this));this.C.push(g.PF("yt-remote-connection-change",this.sS,this));this.C.push(g.PF("yt-remote-receiver-availability-change",this.jC,this));this.C.push(g.PF("yt-remote-auto-connect",this.qS,this));this.C.push(g.PF("yt-remote-receiver-resumed",this.pS,this));this.jC()};
g.h.load=function(){this.g.Dt();g.DV.prototype.load.call(this);this.B=new m9(this,this.g,this.l);var a=(a=jDa())?a.currentTime:0;var b=k9()?new H8(f9(),void 0):null;0==a&&b&&(a=D8(I8(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));mDa(this,this.D,this.D);g.z0(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.A=this.o;g.Ze(this.B,this.l);this.l=this.B=null;g.DV.prototype.unload.call(this);g.z0(this.g.app,5)};
g.h.V=function(){g.QF(this.C);g.DV.prototype.V.call(this)};
g.h.Gl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.JA.apply(this.B,[a].concat(g.oa(c)))};
g.h.CI=function(){return this.loaded?this.B.suggestion:null};
g.h.Nf=function(){return this.l?I8(this.l).Nf:!1};
g.h.hasNext=function(){return this.l?I8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.uN=function(){var a=I8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+B8(a):a.A,isPeggedToLive:1>=(a.C?a.o+B8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+B8(a):a.o,seekableStart:0<a.B?a.B+B8(a):a.B}};
g.h.vN=function(){this.l&&this.l.vE()};
g.h.wN=function(){this.l&&this.l.wE()};
g.h.DP=function(a){1==a&&(this.I=this.l?I8(this.l):null)};
g.h.sS=function(){var a=k9()?new H8(f9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ye(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.nA(a.videoId,D8(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.jC=function(){this.F=[this.o].concat(gDa());var a=g9()||this.o;v9(this,a);this.g.ua("onMdxReceiversChange")};
g.h.qS=function(){var a=g9();v9(this,a)};
g.h.pS=function(){this.A=g9()};
g.h.tN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?x8():v9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&x8(),!0):!1}};
g.h.xN=function(){M8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Nc=function(){return!1};g.uY.remote=u9;})(_yt_player);
